apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test
      image: gcr.io/google-samples/node-hello:1.0
      env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
