apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: firas2
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIcE1JR1FBZ0VBTUJBeERqQU1CZ05WQkFNVEJXWnBjbUZ6TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRU1HR1dJYVZTaWUyTFZKaXVrM0JlOGU2SFY2UnlKd1VKSUp4OS95OWhab1F1THFWaXNKMTRHZUJVClpEUllGRzU2VjJnVXZMcHU4SGEydXZnOEhMaXZPS0FlTUJ3R0NTcUdTSWIzRFFFSkRqRVBNQTB3Q3dZRFZSMFIKQkFRd0FvSUFNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUUMwK080TFp4ZlpDcFFOQUdvaWNvM2xMME5NTWhhLwp4ejN2a254NGQ3RkJHZ0lnSU1jOHp3UkJjTkt1bW81bEVTek5YRmNDK3h4c0lqU2tlQVlFWSt0NzdUOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  usages:
  - digital signature
  - key encipherment
  - server auth
